// Generated by Supabase CLI
// Placeholder types until you can properly generate them

export type Database = {
	public: {
		Tables: {
			photos: {
				Row: {
					id: string;
					event_id: string;
					image: string;
					public_url: string | null;
					caption: string | null;
					uploaded_by_user_id: string | null;
					created_at: string;
					updated_at: string;
				};
				Insert: {
					id?: string;
					event_id: string;
					image: string;
					public_url?: string | null;
					caption?: string | null;
					uploaded_by_user_id?: string | null;
					created_at?: string;
					updated_at?: string;
				};
				Update: {
					id?: string;
					event_id?: string;
					image?: string;
					public_url?: string | null;
					caption?: string | null;
					uploaded_by_user_id?: string | null;
					created_at?: string;
					updated_at?: string;
				};
			};
			users: {
				Row: {
					id: string;
					first_name: string | null;
					last_name: string | null;
					email: string | null;
					job_category: string | null;
					job_title: string | null;
					profile_image: string | null;
					role: string;
					newsletter_subscribed: boolean;
					created_at: string;
					updated_at: string;
				};
				Insert: {
					id: string;
					first_name?: string | null;
					last_name?: string | null;
					email?: string | null;
					job_category?: string | null;
					job_title?: string | null;
					profile_image?: string | null;
					role?: string;
					newsletter_subscribed?: boolean;
					created_at?: string;
					updated_at?: string;
				};
				Update: {
					id?: string;
					first_name?: string | null;
					last_name?: string | null;
					email?: string | null;
					job_category?: string | null;
					job_title?: string | null;
					profile_image?: string | null;
					role?: string;
					newsletter_subscribed?: boolean;
					created_at?: string;
					updated_at?: string;
				};
			};
			// Add other tables as needed
		};
	};
};
